### ISSUE TITLE
🚀 Publish `2.2.1`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/renchan-core#2]
# Overview

Publish version as `2.2.1`.

# Tasks

- [x] ~⚙️ Update package version to `2.2.1`~ ✅️
- [x] Publish by procedure
- [x] ~⚙️ Merge to `main` as `2.2.1`~ ✅️
- [x] Push version tag `2.2.1` on main

<br>
<br>

# Prepare by Publisher

## (1) Confirm version of environment

- [x] Node.js version `v20.14.0`
- [x] npm version `10.9.0`

## (2) Confirm Exporting Contents

- [x] To export new features correctly
- [x] Confirm version in `package.json`
- [x] Confirm version in `package-lock.json`

<br>
<br>

# Confirm to Publish

## (1) Pick up Target Commit Hash to Publish

- [x] git fetch origin --prune
- [x] git log --graph --oneline --decorate --all
- [x] target commit as: `46d9b83`

## (2) Publish with `--dry-run`

- [x] Confirm on target commit hash

  ```
  git diff 46d9b83
  ```

- [x] Confirm no differences

  ```sh
  git status
  ```

- [x] Report publishing logs with `--dry-run` in the comments of this issue

  ```
  npm publish --dry-run
  ```

  Sample logs as follows:

  ```
  % npm publish --dry-run
    npm notice
    npm notice 📦  @openreachtech/renchan@2.2.1
    npm notice Tarball Contents
    npm notice 7.7kB README.ja.md
    npm notice 6.5kB README.md
    npm notice 5.4kB index.js
    npm notice 560B lib/globals/env.cjs
    npm notice 556B lib/globals/env.js
    npm notice 105B lib/globals/root-path.js
    npm notice 1.4kB lib/server/express/routes/BaseExpressRoute.js
    npm notice 797B lib/server/express/routes/GetMethodExpressRoute.js
    npm notice 184B lib/server/express/routes/HttpMethodExpressRoute.js
    npm notice 763B lib/server/express/routes/MiddlewareExpressRoute.js
    npm notice 784B lib/server/express/routes/PostMethodExpressRoute.js
    npm notice 7.9kB lib/server/graphql/BaseGraphqlServerEngine.js
    npm notice 5.8kB lib/server/graphql/contexts/BaseGraphqlContext.js
    npm notice 2.4kB lib/server/graphql/contexts/BaseGraphqlShare.js
    npm notice 3.0kB lib/server/graphql/contexts/GraphqlVisa.js
    npm notice 311B lib/server/graphql/errors/concretes/ConcreteMemberNotFoundGraphqlError.js
    npm notice 2.2kB lib/server/graphql/errors/RenchanGraphqlError.js
    npm notice 4.8kB lib/server/graphql/GraphqlHttpHandlerBuilder.js
    npm notice 3.2kB lib/server/graphql/GraphqlSchemaBuilder.js
    npm notice 9.3kB lib/server/graphql/GraphqlServerBuilder.js
    npm notice 578B lib/server/graphql/resolvers/BaseMutationResolver.js
    npm notice 267B lib/server/graphql/resolvers/BaseQueryResolver.js
    npm notice 4.7kB lib/server/graphql/resolvers/BaseResolver.js
    npm notice 3.3kB lib/server/graphql/resolvers/BaseSubscriptionResolver.js
    npm notice 3.3kB lib/server/graphql/resolvers/ExceptionCatchingProxyBuilder.js
    npm notice 1.6kB lib/server/graphql/resolvers/FilterSchemaHashBuilder.js
    npm notice 10.4kB lib/server/graphql/resolvers/GraphqlResolversBuilder.js
    npm notice 1.4kB lib/server/graphql/resolvers/GraphqlResolversLoader.js
    npm notice 2.3kB lib/server/graphql/resolvers/ResolverSchemaHashBuilder.js
    npm notice 4.0kB lib/server/graphql/scalars/BaseScalar.js
    npm notice 1.4kB lib/server/graphql/scalars/concretes/BigNumberScalar.js
    npm notice 940B lib/server/graphql/scalars/concretes/DateTimeScalar.js
    npm notice 1.8kB lib/server/graphql/scalars/ScalarHashBuilder.js
    npm notice 1.8kB lib/server/graphql/schemas/SchemaFilesLoader.js
    npm notice 1.5kB lib/server/graphql/subscription/ChannelGenerator.js
    npm notice 4.0kB lib/server/graphql/subscription/pubsub/BasePubSub.js
    npm notice 2.1kB lib/server/graphql/subscription/pubsub/LocalPubSub.js
    npm notice 3.4kB lib/server/graphql/subscription/pubsub/RedisPubSub.js
    npm notice 3.0kB lib/server/graphql/subscription/pubsub/tools/EventHub.js
    npm notice 2.8kB lib/server/graphql/subscription/SubscriptionBroker.js
    npm notice 3.9kB lib/server/graphql/subscription/TopicReceiver.js
    npm notice 6.9kB lib/server/restfulapi/BaseRestfulApiServerEngine.js
    npm notice 5.4kB lib/server/restfulapi/contexts/BaseRestfulApiContext.js
    npm notice 1.7kB lib/server/restfulapi/contexts/BaseRestfulApiShare.js
    npm notice 2.5kB lib/server/restfulapi/contexts/RestfulApiVisa.js
    npm notice 335B lib/server/restfulapi/errors/concretes/ConcreteMemberNotFoundRestfulApiError.js
    npm notice 2.1kB lib/server/restfulapi/errors/RenchanRestfulApiError.js
    npm notice 1.1kB lib/server/restfulapi/interfaces/RestfulApiRequest.js
    npm notice 4.3kB lib/server/restfulapi/interfaces/RestfulApiResponse.js
    npm notice 432B lib/server/restfulapi/renderers/BaseGetRenderer.js
    npm notice 494B lib/server/restfulapi/renderers/BasePostRenderer.js
    npm notice 5.8kB lib/server/restfulapi/renderers/BaseRenderer.js
    npm notice 9.2kB lib/server/restfulapi/RestfulApiRoutesBuilder.js
    npm notice 6.5kB lib/server/restfulapi/RestfulApiServerBuilder.js
    npm notice 2.7kB lib/tools/DeepBulkClassLoader.js
    npm notice 1.1kB lib/tools/RootPath.js
    npm notice 1.4kB lib/tools/ValueTemplateHydrator.js
    npm notice 2.4kB package.json
    npm notice 606B types/express.d.ts
    npm notice 5.2kB types/graphql.d.ts
    npm notice 397B types/renchan.d.ts
    npm notice 2.6kB types/restfulapi.d.ts
    npm notice Tarball Details
    npm notice name: @openreachtech/renchan
    npm notice version: 2.2.1
    npm notice filename: openreachtech-renchan-2.2.1.tgz
    npm notice package size: 34.7 kB
    npm notice unpacked size: 185.6 kB
    npm notice shasum: 2f2b3cdfeaeae855d90b5a51dbd2c33124db96d2
    npm notice integrity: sha512-ufgPxPivxNMdL[...]kfGo4Rtf9+NcA==
    npm notice total files: 62
    npm notice
    npm notice Publishing to https://npm.pkg.github.com with tag latest and default access (dry-run)
    + @openreachtech/renchan@2.2.1
  ```

## (3) Confirm Logs with `--dry-run` by Other Member before Actual Publishing

- [x] Confirm Node version `v20.14.0`

  ```sh
  node -v
  ```

- [x] Confirm npm version `10.9.0`

  ```sh
  npm -v
  ```

- [x] Move to target commit hash

  ```sh
  git checkout 46d9b83
  ```

- [x] Report publishing logs with `--dry-run` in the comments of this issue

  ```
  npm publish --dry-run
  ```

<br>
<br>

# Publish

## (4) Publish Actually

- [x] Confirm login user

  ```
  npm whoami --registry https://npm.pkg.github.com
  ```

- [x] npm login to GitHub Packages before publishing if requires

  1. Get login password from your GitHub settings<br>Go to → https://github.com/settings/tokens
  2. Copy your `personal access token` created
  3. Login

      ```sh
      npm login --registry=https://npm.pkg.github.com/
      ```

      ```sh
      Username: your-github-account-in-lower-case-only
      Password:
      Email: your.mail.account@gmail.com
      Logged in as [your-name] on https://npm.pkg.github.com/.
      ```

- [x] Last Confirm

  ```sh
  git status
  ```

  ```sh
  git diff 46d9b83
  ```

- [x] Publish

  When publish as OSS, use options of `--access public`

  ```sh
  npm publish
  ```

## (5) Confirm Access Right of Published Package

- When public module, check by installing package
- When ORT private module, check it below in package page
- Confirm check of `Inherit access from source repository (recommended)`

  ```
  https://github.com/orgs/openreachtech/packages/npm/__package__name__/settings
  ```
