### ISSUE TITLE
⚒️ Define getters of `FileContentReader`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/renchan-core#55]
# Note

Define getters of `#file`

# Tasks

- [x] Define `FileContentReader#get:filename`
- [x] Define `FileContentReader#get:mimetype`
- [x] Define `FileContentReader#get:encoding`
